<?php
/**
 * Facebook Like Button
 *
 * @category    Social Share Buttons
 * @package     Tebet_SocialShare
 * @copyright   Copyright (c) 2012 Firman Efendi (firman.efendi@gmail.com)
 * @website		http://www.theyoungcandidate.com/
 */
?>

<?php if($this->getIsLikeEnabled()): ?>
<!-- Facebook Like Button -->
<div <?php echo $this->writeAttributes() ?>></div>
<!-- End of Facebook Like Button -->
<?php endif; ?>
