<?php
/**
 * Pinterest Pin It Button
 *
 * @category    Social Share Buttons
 * @package     Tebet_SocialShare
 * @copyright   Copyright (c) 2012 Firman Efendi (firman.efendi@gmail.com)
 * @website     http://www.theyoungcandidate.com/
 */
?>

<?php if ($this->getIsPinitEnabled()): ?>
    <!-- Pinterest Pin It Button -->
    <a <?php echo $this->writeAttributes(); ?>>
        <img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" />
    </a>
    <!-- End of Pinterest Pin It Button -->
<?php endif; ?>
