<?php
/**
 * Google +1 Button
 *
 * @category    Social Share Buttons
 * @package     Tebet_SocialShare
 * @copyright   Copyright (c) 2012 Firman Efendi (firman.efendi@gmail.com)
 * @website     http://www.theyoungcandidate.com/
 */
?>

<?php if ($this->getIsPlusoneEnabled()): ?>
    <!-- Google +1 Button -->
    <div <?php echo $this->writeAttributes(); ?>></div>
    <!-- End of Google +1 Button -->
<?php endif; ?>
