<?php
/**
 * Twitter Tweet Button
 *
 * @category    Social Share Buttons
 * @package     Tebet_SocialShare
 * @copyright   Copyright (c) 2012 Firman Efendi (firman.efendi@gmail.com)
 * @website		http://www.theyoungcandidate.com/
 */
?>

<?php if ($this->getIsTweetEnabled()): ?>
    <!-- Twitter Tweet Button -->
    <a <?php echo $this->writeAttributes(); ?>>Tweet</a>
    <!-- End of Twitter Tweet Button -->
<?php endif; ?>
